### ISSUE TITLE
DetailView.jsx:244 Uncaught (in promise) TypeError: Cannot read property 'toUpperCase' of null

### ISSUE THREAD

**Issue by gijs** [nens/G4AW-lizard-client#115]
[Zie hier](https://github.com/nens/G4AW-lizard-client/blob/master/src/components/views/DetailView.jsx#L244)

Het zit 'm in deze variabele:`{parcel.GrowthStage.toUpperCase()}`

![screen shot 2017-07-11 at 10 24 37](https://user-images.githubusercontent.com/7193/28059064-31873428-6623-11e7-9de3-cf8e8a8597ad.jpg)

**Comment by d-weeteling** [comment]
Die GrowthStage is soms niet ingevuld in de backend. Dit geldt voor "buren"/boeren die niet aangesloten zijn bij Campina Vietnam. Het beste is om voor deze percelen een aangepaste (=gesimplificeerde) DetailView te tonen.

**Comment by gijs** [comment]
Mag deze dicht?

**Comment by gijs** [comment]
Fixed in https://github.com/nens/G4AW-lizard-client/pull/134
