### ISSUE TITLE
Add LocTroi logo to home screen

### ISSUE THREAD

**Issue by gijs** [nens/G4AW-lizard-client#124]
Hopefully there's an SVG or EPS of this logo out there.

**Comment by d-weeteling** [comment]
Het staat inmiddels op de transfer, bij mij is het path: /mnt/transfer/dirk/

2017-07-18 8:53 GMT+02:00 Gijs Nijholt <notifications@github.com>:

**Comment by gijs** [comment]
👍

**Comment by gijs** [comment]
![aci](https://user-images.githubusercontent.com/7193/28309819-d2d9f324-6baa-11e7-8eb8-88c0cf8f5235.png)
![groot](https://user-images.githubusercontent.com/7193/28309821-d2de67ec-6baa-11e7-9130-b0a06f1a1193.png)
![klein](https://user-images.githubusercontent.com/7193/28309820-d2dddc00-6baa-11e7-855c-dd1e4e91744a.jpg)

**Comment by gijs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Het logo van Loc Troi moet in de applicatie komen [0,5]](https://trello.com/c/ye9ut7vz/1999-het-logo-van-loc-troi-moet-in-de-applicatie-komen-05)

**Comment by gijs** [comment]
Added when https://github.com/nens/G4AW-lizard-client/pull/130 is merged into master.
