### ISSUE TITLE
Change HEX codes in src/store/Store.js 

### ISSUE THREAD

**Issue by wsu93** [nens/G4AW-lizard-client#183]
@gijs
Can we change the colours used for pests and diseases?
Sorry, I'm not authorized for a pull request ;).

These are specified here src/store/Store.js on Line 200.
From: `          ["#bfc2bb", "#e5907d", "#95786f"]`
**To: `          ["#eb2fcc", "#d52300", "#532700"]`**

**Comment by gijs** [comment]
Yes we can: https://github.com/nens/G4AW-lizard-client/pull/184
Will be merged when @d-weeteling has returned from leave :)
