### ISSUE TITLE
Change HEX codes in src/store/Store.js #2

### ISSUE THREAD

**Issue by wsu93** [nens/G4AW-lizard-client#186]
@gijs 
Can we change the colours used for the legend of Loctroi, Other and LocTroiOutdated?
These are specified here src/store/Store.js on Line 154.

From: `["#000000", "#B6AEA8", "#FFFFFF"]`
To: `["#000000", "#BFBFC6", "#4D4D50"]`

**Comment by gijs** [comment]
Fixed in https://github.com/nens/G4AW-lizard-client/commit/e4a2b9d79fe0492bbd0aa92df3f5c66c13ed9ee0
