### ISSUE TITLE
Minor changes Sat4Rice app

### ISSUE THREAD

**Issue by keesol-nens** [nens/G4AW-lizard-client#187]
# Request for some minor changes in Sat4Rice design:

- In Vietnamese language version:
	- Settings --> Second menu ('Cac Mau Du Lieu')
		- Selection icons still feature W and O, referring to English Weekly and Once
			- We suggest changing the W to H and the O to M
		- Text at the bottom of the boxes stretches beyond icon, please widen the boxes so text will fit
	- Settings --> Third Menu ('Tro Giup')
		- In Vietnamese help text, two fields at bottom do not get translated even though translation is available in the JSON file. (Fields 'Fill in  one-time information at the start of the season' and 'A form 		that allows to send weekly updates on the current status of the rice growth')
	- Language JSONs '/locales/vi/translation.json' and 'locales/en/translation.json' have been updated:
	   --> New text field 'Flooded' added, in legend op flooding map
	   --> New field 'Good' added, as answer to question 'Crop Condition' in farmer data overview.

- Legend (Rice fields): Please change order to 'Loc Troi', 'Loc Troi (outdated)', 'Other' with corresponding colours black, dark gray, light gray)

Thanks!

**Comment by Derryrover** [comment]
archive repo
