### ISSUE TITLE
HeaderBar component: Map background broken

### ISSUE THREAD

**Issue by gijs** [nens/G4AW-lizard-client#73]
The HeaderBar component was designed (and developed) to be able to show a non-clickable map of the parcel. That doesnt work anymore:

![screen shot 2017-06-26 at 15 53 44](https://user-images.githubusercontent.com/7193/27542477-a5c484d2-5a87-11e7-92ae-e82f89687a16.jpg)

**Comment by d-weeteling** [comment]
This works here, maybe something is wrong with your configuration/you don't have the latest `lizard-api-client` code?

**Comment by gijs** [comment]
Could be! I'll re-run npm link etc...
