### ISSUE TITLE
TODO: Add boundingbox to search request if geolocation enabled

### ISSUE THREAD

**Issue by gijs** [nens/G4AW-lizard-client#96]
(back-end will be ready next tuesday)

**Comment by d-weeteling** [comment]
Fixed: whether geolocation is enabled or not, we now always send the bbox to the api/v3/search endpoint.
This bbox is always set: (i) after user logs in we have the default bbox; (ii) if user enables geolocation, he is automatically redirected to the mapView with his location in the middle of the screen/map; (iii) is uder is MapView the bbox is updated by him panning/zooming the map.

**Comment by gijs** [comment]
👍
